Validatejs self exclusion
binary-com/binary-next-gen pull request #620
Opened 2017-07-03 09:50 UTC by nazaninreihani

2017-07-04 04:36 UTC, arnabk requested changes
@nazaninreihani I have couple of concerns with this implementation.

1. Have you considered validatejs just because I told you or you found it to be better than aprovejs?

2. This code looks like monolithic. You have to separate code an do it modular way. First create file called selfexclusion.validation.config.js and define your validation JSON in that file. This files should be imported in this file.

2. Flag 1/Flag 2 -> why do you have to use document.querySelector? This scares me when I see them in ReactJS code

3. Flag 3 -> Lot of bolierplate code here. Please do yarn add lodash/head and import head later in the code. You can replace code like `&& errors && errors.max_balance && <ErrorMsg text={errors.max_balance[0]} />` to `&& <ErrorMsg text={head((errors || {}).max_balance)} />`

4. I do not see any test code for all the changes you have done. Are you sure we do not need them?

2017-07-04 04:36 UTC, arnabk commented on src/settings/SettingsSelfExclusion.js
> +    this.form = document.querySelector('form#settings-self-exclusion');
flag 1

2017-07-04 04:36 UTC, arnabk commented on src/settings/SettingsSelfExclusion.js
> +			<form className="settings-self-exclusion" id="settings-self-exclusion" onSubmit={this.onFormSubmit}>
flag 2

2017-07-04 04:36 UTC, arnabk commented on src/settings/SettingsSelfExclusion.js
> +				{touched.max_balance && errors && errors.max_balance && <ErrorMsg text={errors.max_balance[0]} />}
flag 3

2017-07-17 11:25 UTC, nazaninreihani commented
@arnabk I think validate.js is more stable and suitable for us.
I fixed issues and added some tests can you please review now?

2017-07-18 01:41 UTC, arnabk commented
@nazaninreihani All changes look good. I see that you added `enzyme-react-intl`. What for?

2017-07-19 07:17 UTC, nazaninreihani commented
When using "Enzyme" and "React-Intl" some kind of issue happens in testing, It's for testing components that use "React-Intl's" components or injected formatting functions, so I added it to be able to use mount from "Enzyme".

2017-07-19 17:23 UTC, arnabk commented
@nazaninreihani Is this PR complete and ready to be merged? Do you have more changes to do? Could you please move the card in trello to Review so that I could release this?

2017-07-19 17:23 UTC, arnabk approved these changes

2017-07-20 09:33 UTC, nazaninreihani commented
@arnabk yes this is ready to be merged, I moved the card, Thanks :)

2017-07-20 11:05 UTC, nazaninreihani commented
@arnabk I just found out that all fields are required only if they have value now, so please let me fix this, thanks

2017-07-24 11:28 UTC, nazaninreihani commented
@arnabk it's now ready

2017-07-24 16:01 UTC, merged